### ISSUE TITLE
TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by umiyo** [nuxt-community/nuxtent-module#115]
```
TypeError: Cannot read property 'attributes' of undefined
    at Object.get attributes [as attributes] (/demo/node_modules/nuxtent/dist/module.js:1:1457)
    at /demo/node_modules/nuxtent/dist/module.js:1:455
    at Set.forEach (native)
    at Object.create (/demo/node_modules/nuxtent/dist/module.js:1:398)
    at /demo/node_modules/nuxtent/dist/module.js:1:3450
    at Array.map (native)
    at Object.findAll (/demo/node_modules/nuxtent/dist/module.js:1:3425)
    at /demo/node_modules/nuxtent/dist/module.js:1:14214
    at Array.forEach (native)
    at /demo/node_modules/nuxtent/dist/module.js:1:13942
    at Array.forEach (native)
    at buildContent (/demo/node_modules/nuxtent/dist/module.js:1:13739)
    at Nuxt.<anonymous> (/demo/node_modules/nuxtent/dist/module.js:1:4698)
    at Nuxt.<anonymous> (/demo/node_modules/tappable/lib/index.js:26:26)
    at Nuxt.applyPluginsAsyncSeries (/demo/node_modules/tapable/lib/Tapable.js:206:13)
    at P (/demo/node_modules/pify/index.js:49:6)
```

It worked all well yesterday, but gave me the error now. I have no idea about it.

Following is my code:
```
asyncData: async({ app } => {
   articles: await app.$content('/') .getAll()
})
```

**Comment by dahrens** [comment]
May you please provide one of your content files and also relevant code in the template?

**Comment by alidcastano** [comment]
There's a space between $content and getAll(), that could possibly be the problem. If not ^^

**Comment by dahrens** [comment]
It is not a problem - I tried that in a node shell already ;)

**Comment by alidcastano** [comment]
@umiyo Please also providing your OS

**Comment by umiyo** [comment]
@alidcastano  I have no idea to repeat it. Now it's all well.
