### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null

### ISSUE THREAD

**Issue by zcabjro** [nuxt-community/nuxtent-module#116]
Simply follow the getting started instructions. Steps to reproduce
```
vue init nuxt-community/content-template my-site
cd my-site
npm install
npm run generate
```

```WARNING in ./content/HelloWorld.comp.md
Module build failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at getSection (path\to\my-site\node_modules\nuxtent\dist\loader.js:19:33)
    at Object.module.exports (path\to\my-site\node_modules\nuxtent\dist\loader.js:114:19)
 @ ./content \.comp\.md$
 @ ./.nuxt/plugins.markdownComponents.template.50d8d6b4.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js```

**Comment by zcabjro** [comment]
Duplicate #94
