### ISSUE TITLE
Sitemap integration & localhost instance

### ISSUE THREAD

**Issue by menteora** [nuxt-community/nuxtent-module#123]
Hi, I have a problem with the sitemap module integration.
- I looked at your example: https://github.com/nuxt-community/nuxtent-module/tree/master/examples/sitemap

- Here is my configuration:
```
sitemap: {
    hostname: 'http://nuxt.dinamicamente.org',
    generate: true, // Enable me when using nuxt generate
    routes: () => {
      return Axios.get('http://localhost:3000/content-api').then(res => {
        return res.data['content-endpoints']
      }).then(endpoints => {
        return Promise.all(endpoints.map(endpoint => {
          return Axios.get(`http://localhost:3000/content-api${endpoint}`)
        }))
      }).then(endpoints => {
        return endpoints.reduce((routes, endpoint) => {
          return routes.concat(endpoint.data.map(page => page.permalink))
        }, [])
      })
    }
  }
```
## First Case
- If I run `npm run generate` `http://localhost:3000/content-api` is not available and the sitemap.xml is not generated

```
> nuxt-example@1.0.0 generate /home/menteora/Projects/Vue/nuxt-blog
> nuxt generate

  nuxt:generate Generating... +0ms
  nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: /_nuxt/content) +0ms
  nuxt:build App root: /home/menteora/Projects/Vue/nuxt-blog +0ms
  nuxt:build Generating /home/menteora/Projects/Vue/nuxt-blog/.nuxt files... +0ms
  Error: connect ECONNREFUSED 127.0.0.1:3000

  nuxt:build Generating files... +54ms
  nuxt:build Generating routes... +13ms
  Error: connect ECONNREFUSED 127.0.0.1:3000

  nuxt:build Building files... +69ms
  build [=======             ] 35%
```
## Second Case
- If I run `npm run dev` that opens `http://localhost:3000/content-api` and I run `npm run generate` the `sitemap.xml` is generated correctly, but the command `generate` doesn't want another instance of `localhost` open.

```
> nuxt-example@1.0.0 generate /home/menteora/Projects/Vue/nuxt-blog
> nuxt generate

  nuxt:generate Generating... +0ms
  nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: /_nuxt/content) +0ms
  nuxt:build App root: /home/menteora/Projects/Vue/nuxt-blog +0ms
  nuxt:build Generating /home/menteora/Projects/Vue/nuxt-blog/.nuxt files... +1ms
  nuxt:build Generating files... +36ms
  nuxt:build Generating routes... +12ms
  nuxt:build Building files... +97ms
Build completed in 40.932s

Hash: 99b7fa7aec843284d082
Version: webpack 3.8.1
Time: 40945ms
                                                                                                                       Asset       Size  Chunks                    Chunk Names
                                                                                  content/news/news.trova-le-differenze.json    1.23 kB          [emitted]
                                                                                                  img/darthvader.efb62bb.jpg    57.4 kB          [emitted]
                                                                                         pages/_page.cd98344329429a50cad9.js    2.43 kB       0  [emitted]         pages/_page
                                                                                    pages/tags/index.0417f32ceca976298397.js    18.7 kB       1  [emitted]         pages/tags/index
                                                                                         pages/index.daba7278ccff0eb4fb44.js    2.28 kB       2  [emitted]         pages/index
                                                                                    pages/tags/_post.e9f11b1cd976b491e612.js    5.69 kB       3  [emitted]         pages/tags/_post
                                                                                    pages/news/_post.c9bc5cebf078258959db.js    5.71 kB       4  [emitted]         pages/news/_post
                                                                                     layouts/default.8f5ca6abb6f7c93b9eb1.js     3.5 kB       5  [emitted]         layouts/default
                                                                                           pages/404.5d0ecbddb49d2a782f53.js  985 bytes       6  [emitted]         pages/404
                                                                                              common.854b933380baca557694.js     350 kB       7  [emitted]  [big]  common
                                                                                                 app.02c63f34940fa24c278f.js    62.1 kB       8  [emitted]         app
                                                                                            manifest.99b7fa7aec843284d082.js    1.81 kB       9  [emitted]         manifest
                                                                                 common.6e45baa8ca9f6f9c47829b7c1870bc8e.css     286 kB       8  [emitted]         app
                                                                                                                    LICENSES  868 bytes          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part8.json    14.1 kB          [emitted]
                                                   content/news/news.ideone-testiamo-online-il-codice-senza-compilatore.json    4.26 kB          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part7.json      30 kB          [emitted]
                                                content/news/news.come-identificare-ed-installare-un-driver-sconosciuto.json    3.85 kB          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part6.json    15.2 kB          [emitted]
                                               content/news/news.installare-ruby-on-rails-4-linux-mint-e-ubuntu-parte-2.json    6.17 kB          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part5.json    15.3 kB          [emitted]
                                                                      content/news/news.dinamicamente-torna-dalle-ferie.json    1.28 kB          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part4.json    29.7 kB          [emitted]
                                                               content/news/news.introduzione-a-ruby-on-rails-4-parte-1.json    5.62 kB          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part3.json    6.29 kB          [emitted]
                                                  content/news/news.come-diventare-un-mago-di-javascript-con-codecombat.json    7.27 kB          [emitted]
                                                                           content/news/news.le-novita-di-drupal8-part2.json    4.73 kB          [emitted]
                                                    content/news/news.dinamicamente-x2-ora-anche-su-google-play-edicola.json    3.62 kB          [emitted]
                                                                                               img/dinamicamente.a9a02e1.png      14 kB          [emitted]
                                                                       content/news/news.tutti-pronti-per-drupal8-part1.json    4.05 kB          [emitted]
                                         content/news/news.come-imparare-nuovi-linguaggi-web-semplicemente-divertendosi.json    4.26 kB          [emitted]
                                                                        content/news/news.l-importanza-della-pagina-404.json    3.52 kB          [emitted]
                                                                 content/news/news.hai-troppe-cose-da-fare-prova-trello.json    5.87 kB          [emitted]
                                                        content/news/news.migrare-un-blog-a-jekyll-da-altre-piattaforme.json    3.08 kB          [emitted]
                                                          content/news/news.sei-un-perfezionista-applica-il-metodo-kiss.json    4.25 kB          [emitted]
                                                   content/news/news.sotto-al-cofano-di-dinamicamente-jekyll-e-markdown.json     5.6 kB          [emitted]
                                                                       content/news/news.dinamicamente-org-cambia-volto.json    1.85 kB          [emitted]
content/news/news.metto-un-appunamento-sul-calendario-e-mi-arriva-il-promemoria-via-sms-sto-parlando-di-google-calendar.json    2.78 kB          [emitted]
                                                    content/news/news.creare-un-sito-alla-velocit-della-luce-con-drupal.json    6.05 kB          [emitted]
                                                                            content/news/news.dinamicamente-si-aggiorna.json    3.51 kB          [emitted]
                                                    content/news/news.esportare-i-propri-contatti-da-un-cellulare-nokia.json     2.5 kB          [emitted]
                                                             content/news/news.drupalcamp-2011-impressioni-e-sensazioni.json    10.5 kB          [emitted]
                                                                  content/news/news.il-drupalcamp-2011-approda-a-verona.json    1.87 kB          [emitted]
                                                       content/news/news.installare-uneditor-wysiwyg-su-drupal-ckeditor.json    6.27 kB          [emitted]
                                   content/news/news.come-montare-limmagine-di-un-disco-sul-device-di-loopback-di-linux.json    4.61 kB          [emitted]
                                          content/news/news.facebook-blocca-lesportazione-dei-contatti-e-google-cosa-fa.json    1.33 kB          [emitted]
                                                                   content/news/news.come-modificare-i-form-in-drupal-6.json    5.78 kB          [emitted]
                                          content/news/news.drupal-e-multilingua-come-rendere-poliglotta-il-vostro-sito.json     7.3 kB          [emitted]
                                                       content/news/news.eclipse-come-usare-gli-spazi-al-posto-dei-tabs.json    1.31 kB          [emitted]
                     content/news/news.dropbox-portableapps-condividere-le-applicazioni-su-tutti-pc-senza-chiavetta-usb.json    5.12 kB          [emitted]
                                                                                    content/news/news.qualcosa-cambiato.json  705 bytes          [emitted]
                                                                                                      content/news/_all.json     243 kB          [emitted]
                                                                                                   content/pages/policy.json    13.9 kB          [emitted]
                                                                                                  content/pages/license.json    2.39 kB          [emitted]
                                                                                                    content/pages/about.json    2.44 kB          [emitted]
                                                                                                     content/pages/_all.json    18.8 kB          [emitted]
 + 14 hidden assets

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets:
  common.854b933380baca557694.js (350 kB)
Hash: 30018545c9955fec5f5e
Version: webpack 3.8.1
Time: 24038ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  448 kB          [emitted]
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1276:14)
    at listen (net.js:1312:10)
    at Server.listen (net.js:1403:7)
    at Function.listen (/home/menteora/Projects/Vue/nuxt-blog/node_modules/express/lib/application.js:618:24)
    at Nuxt.<anonymous> (/home/menteora/Projects/Vue/nuxt-blog/node_modules/nuxtent/dist/module.js:1:4476)
    at Nuxt.<anonymous> (/home/menteora/Projects/Vue/nuxt-blog/node_modules/tappable/lib/index.js:26:26)
    at Nuxt.applyPluginsAsyncSeries (/home/menteora/Projects/Vue/nuxt-blog/node_modules/tapable/lib/Tapable.js:206:13)
    at P (/home/menteora/Projects/Vue/nuxt-blog/node_modules/pify/index.js:49:6)
    at Nuxt.<anonymous> (/home/menteora/Projects/Vue/nuxt-blog/node_modules/pify/index.js:11:9)
    at Nuxt.ret [as applyPluginsAsync] (/home/menteora/Projects/Vue/nuxt-blog/node_modules/pify/index.js:72:32)
    at Generator._callee2$ (/home/menteora/Projects/Vue/nuxt-blog/node_modules/nuxt/lib/builder/generator.js:40:21)
    at tryCatch (/home/menteora/Projects/Vue/nuxt-blog/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/menteora/Projects/Vue/nuxt-blog/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/home/menteora/Projects/Vue/nuxt-blog/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)

npm ERR! Linux 4.8.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "generate"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! nuxt-example@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-example@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nuxt-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nuxt-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nuxt-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/menteora/Projects/Vue/nuxt-blog/npm-debug.log
```
Could be possible a walk-around to by-pass these errors?

Thank You very much for your attention.

**Comment by alidcastano** [comment]
@hochchristoph did you find a solution for this?

**Comment by teamgroove** [comment]
It looks like you had your dev-environment running, when you started the: npm run generate.
"Error: listen EADDRINUSE :::3000" is supicious.
Just terminate your local dev-server before generating with nuxtent.

**Comment by menteora** [comment]
Hi @teamgroove, thank you for your attention.
Yes, this is the second case (I clarify my issue putting titles).
The first case is without dev server running.

Sitemap require dev server running, `npm run generate` require dev server not running, that's generate conflict.

**Comment by teamgroove** [comment]
First Case: domain mismatch
http://localhost:3000/content-api
vs:
127.0.0.1

In your config, you need to harmonize these values. Choose one.

**Comment by alidcastano** [comment]
Thanks @teamgroove for help, going to close this
