### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by derevandal** [nuxt-community/nuxtent-module#128]
I'm using Nuxtent from Github and Windows 10 to build.

Command I used:

`yarn build`

Error:

``` bash

{ Error: Cannot find module './dist/module.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\dev\idepead\website\node_modules\nuxtent\index.js:1:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at ModuleContainer._callee2$ (D:\dev\idepead\website\node_modules\nuxt\lib\core\module.js:108:16)
    at tryCatch (D:\dev\idepead\website\node_modules\nuxt\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (D:\dev\idepead\website\node_modules\nuxt\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (D:\dev\idepead\website\node_modules\nuxt\node_modules\regenerator-runtime\runtime.js:117:21) code: 'MODULE_NOT_FOUND' }
```

**Comment by alidcastano** [comment]
Please try again with latest release (^1.2.0)

**Comment by derevandal** [comment]
Fixed. Thanks 😄
