### ISSUE TITLE
'Cannot read property 'get' of undefined' on fresh install

### ISSUE THREAD

**Issue by dunepebbler** [nuxt-community/nuxtent-module#133]
Hi,

I just started a Nuxtent project.
When I click the 'See your first post' button, I get the following error:

`'Cannot read property 'get' of undefined'`

```
app.js:2687 TypeError: Cannot read property 'get' of undefined
    at _callee$ (http://localhost:3000/_nuxt/app.js:1654:33)
    at tryCatch (http://localhost:3000/_nuxt/vendor.js:5207:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/_nuxt/vendor.js:5441:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_nuxt/vendor.js:5259:21)
    at step (http://localhost:3000/_nuxt/vendor.js:268:30)
    at http://localhost:3000/_nuxt/vendor.js:286:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3000/_nuxt/vendor.js:695:28)
    at http://localhost:3000/_nuxt/vendor.js:265:12
    at fetchContent (http://localhost:3000/_nuxt/app.js:1695:20)
```

```
$ node -v                                                       
v9.4.0

$ npm -v
5.6.0

macOS 10.12.6 (Sierra)
```

**Comment by cesasol** [comment]
With nuxt 1.0 this plugins now requires to have the axios module insde the nuxt.conf.js
