### ISSUE TITLE
Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt-community/nuxtent-module#59]
Everything is OK when run dev `nux`.
When I run generate, there is a problem I can't locate it, My nuxtent version is 0.2.77
```
[wi@localhost wi-cuckoo.gitpage]$ npm run generate

> cuckoo@1.0.0 generate /home/wi/bin/wi-cuckoo.gitpage
> NODE_ENV=production nuxtent generate

  nuxt:generate Generating... +0ms
TypeError: Invalid attempt to destructure non-iterable instance
    at /home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxtent/dist/module.js:1:33094
    at Object.findOnly (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxtent/dist/module.js:1:7858)
    at /home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxtent/dist/module.js:1:10334
    at Array.forEach (native)
    at /home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxtent/dist/module.js:1:9864
    at Array.forEach (native)
    at U (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxtent/dist/module.js:1:9693)
    at ModuleContainer.V (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxtent/dist/module.js:1:11973)
    at /home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/lib/core/module.js:133:29
    at ModuleContainer._callee2$ (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/lib/core/module.js:132:12)
    at tryCatch (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/dist/nuxt.js:842:30)
    at /home/wi/bin/wi-cuckoo.gitpage/node_modules/nuxt/dist/nuxt.js:853:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  nuxt:build App root: /home/wi/bin/wi-cuckoo.gitpage +0ms
```

----
## additional
If I change the run dev from nuxt to nuxtent. the error is same. And My nuxtent.config.js is:

```
/*
** nuxtent config
*/

module.exports = {
  content: [
    ['blog', {
      page: '/blog/_slug',
      permalink: "/:slug",
      generate: ['get', 'getAll', 'getOnly', 'query'],
      isPost: false
    }]
  ],
  api: {
   	baseURL: process.env.NODE_ENV === 'production'
	    ? 'http://wi-cuckoo.github.io'
	    : 'http://0.0.0.0:3000'
 	}
}
```

**Comment by alidcastano** [comment]
Remove `query` as that shouldn't be there at all and see if that works. If not, remove `getOnly` and see if that is the problem. Let me know

**Comment by wi-cuckoo** [comment]
@alidcastano As you said. I remove the query and getOnly call in asyncDate hook, and everything goes OK. And further, both the query and getOnly will cause such an error. Maybe it's a bug. So I will view the nuxtent code to see why happened. Also I hope it can be fixed ASAP.

**Comment by alidcastano** [comment]
I added `getOny` and `getBetween` mainly for application builds. For static builds, it might not be fully supported since it requires the generation of all the static assets. 

As an alternative, you can do `getAll` and manipulate the data in the client. 

Also, you can try adding arguments to `getOnly` e.g. ['getOnly', [0, 4]] to see if that is the problem.

**Comment by wi-cuckoo** [comment]
@alidcastano  the query method also can't work as expected in generation. I tested it. The query call is very useful to shorten the response data size. So cat it be fixed?

**Comment by alidcastano** [comment]
I'll have to add this to documentation.

You can pass arguments to each generate method.

```
generate: [
  ['getOnly', { 
       query: { ... }
        args: [....]
   }]
]
```
