### ISSUE TITLE
Error with starter `npm run dev`

### ISSUE THREAD

**Issue by victorkane** [nuxt-community/nuxtent-module#70]
On a Mac (Yosemite)

```
$ node -v
v6.11.2
$ npm -v
3.10.10
```

Followed Quick start instructions:

```
$ vue init nuxt-community/nuxtent-template my-site
$ cd my-site
$ npm install
```

Following successful install, upon running `npm run dev`, following error in up-to-date standard chrome browser content area:

```
Nuxt.js Error:

TypeError: inject is not a function
    at module.exports.__webpack_exports__.default (.nuxt/axios.js:138:2)
    at _callee$ (.nuxt/index.js:117:10)
    at tryCatch (/Users/victorkane/Work/AWebFactory/dev/nuxt/try-nuxtent/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/victorkane/Work/AWebFactory/dev/nuxt/try-nuxtent/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/victorkane/Work/AWebFactory/dev/nuxt/try-nuxtent/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:239:13
```

Suggestions, anyone?

**Comment by victorkane** [comment]
Same error on standard Ubuntu server

**Comment by victorkane** [comment]
This is NOT connected to #53 and occurs with `npm run dev` as well as build and start.

**Comment by turnavies** [comment]
@victorkane I resolved this by adding @nuxtjs/axios^2.1.0 as a dependency

**Comment by victorkane** [comment]
@turnavies Works like a charm, thanks.

**Comment by alidcastano** [comment]
@turnavies Thanks for helping to resolve this!
